# Site settings
title: Elliot's first website!
email: mawbye@carleton.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my first website that I am building using Awesome Inc.'s 
  Jekyll tutorial found on udemy.com'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  mawbye

# Build settings
markdown: kramdown
highlighter: rouge